// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz4omU1bqZ5mvMjsyfJP7AhLajf3jCWRE',
    appId: '1:618367534949:web:cd1137aba539770a18438c',
    messagingSenderId: '618367534949',
    projectId: 'arptc-connect',
    authDomain: 'arptc-connect.firebaseapp.com',
    storageBucket: 'arptc-connect.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLNvV6_9yYtAp9hu0e-PIHqjsDWyegcuQ',
    appId: '1:618367534949:android:b1e583e95a5bd85118438c',
    messagingSenderId: '618367534949',
    projectId: 'arptc-connect',
    storageBucket: 'arptc-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCriAy31F5DTjoRO6996xYle6DEdgox4rE',
    appId: '1:618367534949:ios:92b98be19772654b18438c',
    messagingSenderId: '618367534949',
    projectId: 'arptc-connect',
    storageBucket: 'arptc-connect.appspot.com',
    iosBundleId: 'com.sugar.arptcConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCriAy31F5DTjoRO6996xYle6DEdgox4rE',
    appId: '1:618367534949:ios:a237d1b49462edf018438c',
    messagingSenderId: '618367534949',
    projectId: 'arptc-connect',
    storageBucket: 'arptc-connect.appspot.com',
    iosBundleId: 'com.sugar.arptcConnect.RunnerTests',
  );
}
